apiVersion: apps/v1
kind: Deployment
metadata:
  name: eurekaserver-deployment
  namespace: eurekaserver
  labels:
    app: eurekaserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eurekaserver
  template:
    metadata:
      labels:
        app: eurekaserver
    spec:
      containers:
      - name: eurekaserver
        image: dangngocsoncntt/eurekaserver:latest
        ports:
        - containerPort: 29901
---
apiVersion: v1
kind: Service
metadata:
  name: eurekaserver-service
  namespace: eurekaserver
spec:
  selector:
    app: eurekaserver
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 29901
      targetPort: 29901
